/**
 * Attachment and Sangha Symposium Presentation
 * Wrapper component that configures the generic SymposiumPresentation
 */

import SymposiumPresentation, {
  type SpeakerConfig,
  type FallbackVoice,
  type SymposiumTheme,
} from './SymposiumPresentation';

const SPEAKER_CONFIG: SpeakerConfig[] = [
  { id: 'a-gautama-buddha', name: 'Gautama Buddha', epithet: 'Founder of the Sangha' },
  { id: 'a-nagarjuna', name: 'Nāgārjuna', epithet: 'Philosopher of Emptiness' },
  { id: 'a-vasubandhu', name: 'Vasubandhu', epithet: 'Psychologist of Mind' },
  { id: 'a-dogen', name: 'Dōgen', epithet: 'Practice Radical' },
  { id: 'a-ashoka', name: 'Ashoka', epithet: 'Political Realist' },
  { id: 'a-simone-weil', name: 'Simone Weil', epithet: 'Severe Mystic' },
  { id: 'a-nietzsche', name: 'Friedrich Nietzsche', epithet: 'The Prosecutor', isHeretic: true },
];

const FALLBACK_VOICES: Record<string, FallbackVoice> = {
  'a-gautama-buddha': { voice: 'en-IN-PrabhatNeural', rate: 0.95, language: 'en-IN', accent: 'Indian English, multilingual' },
  'a-nagarjuna': { voice: 'en-IN-PrabhatNeural', rate: 0.96, language: 'en-IN', accent: 'Indian English, analytical, precise' },
  'a-vasubandhu': { voice: 'en-IN-PrabhatNeural', rate: 0.97, language: 'en-IN', accent: 'Indian English, cognitive, systematic' },
  'a-dogen': { voice: 'ja-JP-KeitaNeural', rate: 0.94, language: 'ja-JP', accent: 'Japanese, direct, uncompromising' },
  'a-ashoka': { voice: 'en-IN-PrabhatNeural', rate: 0.95, language: 'en-IN', accent: 'Indian English, regal, reflective, weighty' },
  'a-simone-weil': { voice: 'fr-FR-DeniseNeural', rate: 0.96, language: 'fr-FR', accent: 'French, intense, severe, mystical' },
  'a-nietzsche': { voice: 'de-DE-KatjaNeural', rate: 0.98, language: 'de-DE', accent: 'German, provocative, challenging, intense' },
};

// Generated speeches using ask-faculty edge function
// Target length: ~1050 words per speech (~7 minutes at 150 wpm)
const SPEECHES: Record<string, string> = {
'a-gautama-buddha': `The question that has been raised, that attachment is the root of suffering, yet we gather in villages, in monasteries, in forests, forming a community called the Sangha, seems at first glance a paradox. I will unfold this seeming tension by turning the question itself into a lamp that illuminates the path.  

When I first sat beneath the Bodhi tree, I was alone in the sense that no one stood beside me, yet the forest was full of life—birds, insects, wind, rain. In that solitude I discovered that the mind, when left without support, can drift like a leaf caught in a storm, tossed by desire, aversion, and ignorance. The leaf is not the storm; the storm is the condition of the leaf’s freedom. Likewise, a practitioner who isolates himself from all companionship may appear to have escaped attachment, but he remains attached to the very notion of self‑reliance, to the pride of being beyond need.  

Thus the middle way I taught is not a withdrawal into a desert of solitude, nor a surrender to the crowd of the world, but a balanced shore where the river of practice may be crossed safely. The river is the flow of craving and clinging; the stones are the teachings, the raft is mindfulness, and the companions are the oars that keep the vessel steady. Without oars, even a skilled swimmer may be swept away; with too many oars, the boat becomes heavy and sinks. The Sangha supplies the oars, calibrated to the weight of each traveller.  

Consider the parable of the blind men and the elephant. Each man touches a different part—tusk, leg, side—and declares the elephant to be a spear, a tree, a wall. Their attachment to their limited perception creates confusion and suffering. When they gather, speak, and compare their experiences, the picture of the whole elephant emerges. In the same way, a single practitioner may grasp a fragment of the Dharma, but the community allows the fragments to be woven into a tapestry that reveals the full shape of liberation.  

I have often spoken of the Four Noble Truths as a medicine. The first truth diagnoses the disease—dukkha, the unsatisfactoriness of existence. The second identifies its cause—tanha, the craving that binds us. The third promises a cure—nirodha, the cessation of craving. The fourth prescribes a treatment—magga, the noble eightfold path. A medicine taken alone may be swallowed, but it is the physician’s guidance, the apothecary’s counsel, and the support of fellow patients that ensure the dose is measured, the side effects observed, and the recovery sustained. The Sangha is that physician’s counsel, the community of patients who share their observations, remind one of the dosage, and celebrate each step toward health.  

Why, then, do we build monasteries of wood and stone, invite lay followers into the same refuge, and establish a code of conduct for monks and nuns? Because the very act of building is an expression of the middle way. The structure provides shelter from the heat of desire and the cold of aversion, allowing the mind to settle without the distraction of weather. Yet the structure is not an object of worship; it is a tool, like a bowl that holds water. When the bowl is broken, the water still flows; when the bowl is intact, it serves its purpose. If we clung to the building as sacred, we would have recreated the attachment we seek to dissolve.  

In my early days after awakening, I gathered five companions—Kaundinya, Assaji, Mahanama, Addasaka, and Bhaddiya—who had also walked the path of insight. They were not drawn to me because I claimed a throne of wisdom, but because they recognized in my presence a mirror that reflected their own awakened potential. Together we practiced, questioned, and supported one another. It was not the fame of the teacher that bound them, but the shared aspiration to extinguish the flame of craving. Their presence reminded me, and reminds all of us, that enlightenment is not a solitary star but a constellation whose light is magnified by the proximity of other luminous points.  

Lay followers, too, find a place in the community. A householder who offers alms, who listens to the Dhamma, who observes the five precepts, cultivates virtue in the midst of worldly duties. Their practice does not diminish because they are among monks; rather, it is sharpened by the example of renunciation that surrounds them. The layperson learns that generosity is not merely giving material goods, but also offering the time to listen, the patience to understand, and the compassion to support those who have taken a different path. In this way, the Sangha becomes a garden where each plant, whether a towering tree of monastic discipline or a humble herb of household virtue, contributes to the ecosystem of awakening.  

You may ask: does the community not become a new object of grasping? I answer with a question: when a traveler rests at an inn, does the inn become his destination, or does it simply offer a pause before he continues his journey? The inn is not the goal; it is a convenient shelter. Likewise, the Sangha is not the final liberation, but a refuge that aids the traveler in the middle of the road. When the traveler awakens, he leaves the inn, but he carries with him the lessons of hospitality, cooperation, and mutual respect that were taught there.  

In practice, the community provides three essential supports. First, ethical reinforcement: when a monk sees a fellow monk falter, he gently reminds him of the precept, preventing the seed of ignorance from sprouting. Second, doctrinal clarification: when a disciple misinterprets a teaching, the elder offers a correct exposition, preventing the mind from wandering into dogma or superstition. Third, emotional encouragement: when fatigue settles upon the body, a companion offers a word of kindness, a shared meal, a smile that rekindles the flame of determination. These supports function like the three pillars of a bridge—strength, stability, and balance—allowing the seeker to cross the chasm of suffering without collapse.  

Let us recall the story of the monk Ananda, who once struggled with doubt after hearing a subtle teaching on impermanence. He confided in his fellow monk, and together they examined the breath, observing its arising and passing. The shared observation dissolved the doubt, not because Ananda received a doctrinal answer, but because the presence of another mind, attuned to the same practice, reflected his own experience back to him, confirming the truth he was already living. This is the power of community: it mirrors the mind’s own clarity, allowing the practitioner to see what is already present without distortion.  

In the larger world, the Sangha also serves as a beacon for those who have not yet set foot on the path. A wandering merchant, seeing the calm demeanor of monks, may wonder what sustains such peace amid hunger, heat, and danger. The merchant may then inquire, sit, listen, and perhaps find the seed of curiosity that later blossoms into the desire to practice. Thus the community becomes a doorway, not a wall, inviting all beings to step toward liberation at their own pace.  

I must also acknowledge that the community can become a source of attachment if the members cling to titles, hierarchy, or the prestige of belonging. I warned my disciples to watch the mind that says, “I am a monk, therefore I am above the lay.” Such pride is another form of craving, a desire to be seen as superior. When the mind recognizes this, it must let go of the self‑identification and return to the practice of humility, remembering that the only true distinction is between wholesome and unwholesome actions, not between monk and layperson.  

Therefore, building the Sangha is an intentional act of skillful means. It is a vessel crafted to hold the water of the Dharma, not a statue to be adored. The water flows through the vessel, nourishing the soil of each heart, and when the vessel cracks, the water still finds its way, seeping into the cracks of the world, reaching those who need it most.  

In closing, I return to the image of a river crossing. The river of`,
  'a-nagarjuna': `The words spoken just now by the venerable teacher draw our attention to the paradox that has long troubled seekers: attachment is declared the source of suffering, and yet we gather in villages, in monasteries, in forests, forming the sangha. I hear this tension as a call to examine not only the surface of our practices but the very ground upon which they stand. In my own investigations I have found that the question is not whether we may assemble, but whether we cling to the notion of assembly as something permanent, as if it possessed an essence independent of the causes that bring it forth. If we can see through that clinging, the community becomes a vehicle, not a trap.

Attachment, as I have taught, is the grasping at a self‑nature that does not exist. When a being believes that a feeling, a view, or a gathering has an inherent, unchanging identity, the mind is bound to the wheel of birth and death. The suffering that follows is not the mere presence of the sangha but the grasping at it as a solid refuge, a self‑substance that can guarantee safety. In this mistaken view the community is reified, and the practitioner becomes a hostage of his own expectation that the sangha will protect him from the storm of craving. Thus the root of suffering lies not in the gathering itself, but in the mistaken belief that the gathering possesses an independent reality.

To dissolve this mistake I employ what I call binary dissolution: I show that any proposition about the sangha, when examined, cannot be affirmed as existent in an absolute sense, nor can it be denied as utterly nonexistent. The sangha is not an eternal, unchanging entity, for that would be to ascribe to it an intrinsic nature, which emptiness denies. Yet it is not a mere illusion, for the very causes and conditions that give rise to a community of practitioners are observable: shared discipline, mutual encouragement, the cultivation of the Dharma. By refusing both extremes—affirming a self‑nature and denying any appearance—I place the sangha in the middle way, where it is empty of inherent existence but full of dependent origination.

Dependent origination reveals precisely how the sangha arises. A monk who has taken refuge in the triple gem encounters the teachings, hears the Dharma, and feels the aspiration to practice. The aspiration invites companions, and companions invite further aspiration. Each link in this chain is a cause and condition, none of which is independent. The community is therefore a flux of relationships, a tapestry woven from the threads of ethical conduct, meditation, and wisdom. When we understand that the sangha is nothing beyond these interdependent factors, we see that it is neither a self‑contained sanctuary nor a void; it is a dynamic process that exists only insofar as the conditions are present.

Consider, for example, a monk who sits in meditation beside his fellow practitioners. He may feel a sense of support, a feeling that his practice is strengthened by the presence of others. If he clings to that feeling as the source of his liberation, he is still attached, and his mind remains bound to the notion of a permanent support. But if he recognizes that the support is itself a conditioned phenomenon—arising because of shared intention, mutual respect, and the teachings—then the feeling becomes a skillful means, a temporary aid that can be let go of when its purpose is fulfilled. The practice does not become dependent on the community; rather, the community becomes a vehicle for the cultivation of insight into emptiness.

The danger lies in mistaking the vehicle for the destination. When a practitioner regards the sangha as the ultimate refuge, he creates a new self‑attachment, a self‑identification with the group, a notion of “my sangha, my protection.” This is the very attachment the Buddha warned against, and it reproduces the same cycle of craving and aversion. I have argued that any view that posits a fixed self, whether it is the individual or the collective, must be deconstructed. The sangha, like all phenomena, is empty of intrinsic nature; to treat it otherwise is to fall into the extreme of eternalism.

Yet I do not deny the practical value of the sangha. In the middle way, we employ skillful means, or upāya, to guide beings toward liberation. The community provides a context in which the Dharma can be heard, practiced, and transmitted. It offers the conditions for ethical conduct, for the cultivation of concentration, and for the development of wisdom. When we see the sangha as a provisional support, we can use it without clinging, just as a raft is used to cross a river and then left behind. The emptiness of the sangha does not diminish its efficacy; rather, it frees us to engage with it without the fetters of self‑attachment.

Thus, the question of why we build communities when attachment is the root of suffering is answered by recognizing that the building itself is not an act of attachment if it is undertaken with the insight of emptiness. The community is erected not as a permanent edifice to shelter a self, but as a provisional structure of causes and conditions that facilitate the realization of non‑self. In this light, the sangha becomes a mirror that reflects the interdependence of all phenomena, reminding us that we are not isolated islands but waves arising from the same ocean of dependent origination.

In my own teachings I have often employed the analogy of a lamp. The lamp itself is not the light; the light depends on the oil, the wick, and the surrounding darkness. When the oil is exhausted, the lamp ceases to shine, yet the darkness remains unchanged. The sangha is like the lamp: it provides the oil of moral discipline, the wick of meditation, and the surrounding darkness of ignorance that makes the light visible. When the oil is used up, the lamp goes out, but the darkness does not become a new suffering; it merely returns to its empty nature. By understanding this, we can appreciate the community without becoming attached to its continued existence.

Finally, I invite each of you to examine your own relationship to the sangha. Ask whether you regard it as an immutable refuge or as a contingent aid. See whether your mind clings to the idea of “my sangha” as a source of safety, or whether you allow the community to arise and dissolve in accordance with the law of dependent origination. In doing so, you will discover that the very question of attachment dissolves, as the mind no longer grasps at a self‑nature in the community, nor denies its appearance altogether. The middle way, the path of emptiness, guides us to a place where the sangha is both a source of support and an object of non‑attachment, a place where compassion and wisdom flourish without the burden of clinging.

May our inquiry into emptiness, our practice of dependent origination, and our compassionate engagement with one another lead us beyond the extremes of self‑grasping and nihilism, toward the clear realization that all phenomena, including the sangha, are empty yet efficacious. In this way, we honor the teaching that attachment is the root of suffering while also embracing the wise use of community as a means, not an end. Let us walk together, aware of the emptiness of our steps, yet grateful for the shared path that brings us nearer to the cessation of dukkha.`,
  'a-vasubandhu': `I hear the echo of the earlier voices: the Buddha’s reminder that attachment is the root of suffering, and Nagarjuna’s pointing to the paradox that we, who seek liberation, nevertheless form villages, monasteries, and forests into a community called Sangha. This paradox is not a flaw in the teaching but a sign that the mind itself is woven with patterns that require careful analysis before we can untie the knot of clinging.  

In my own investigations of consciousness, I have always begun by separating the apparent from the ultimate, the manifest flow of mental events from the substratum that stores them. The mind, as I have described in the *Abhidharmakośa* and later in the *Triṃśikā*, consists of a series of momentary cognitions (cittas) that arise, illuminate an object, and cease. Each cognition carries with it a seed (bīja) that is stored in the *ālaya‑citta*, the store‑house consciousness. It is this store‑house that preserves the habitual tendencies, the karmic imprints that predispose us to grasp, to cling, to seek permanence in what is, in truth, a flux.

When we speak of attachment, we are speaking of the operation of those seeds that have taken root in the *ālaya*. They project a sense of self‑existence onto the objects of perception, and then the mind, like a fisherman, pulls the net of desire over the perceived object, believing it to be a source of lasting satisfaction. The suffering that follows is the inevitable consequence of this misapprehension. Yet the very act of gathering into a community is itself a mental event, a cognition that arises from a seed of aspiration: the seed that wishes for support, for guidance, for a mirror in which one may see the distortions of one’s own mind.

If attachment is the root of suffering, why then do we build a Sangha? The answer lies in the distinction between attachment that reinforces the ego‑grasping and the wholesome association that functions as a skillful means (*upāya*). A community, when organized according to the threefold training—ethical conduct (*śīla*), meditation (*samādhi*), and wisdom (*prajñā*)—provides a field in which the mind can observe its own patterns without being overwhelmed by them. In a solitary forest, the mind may still encounter the same seeds, but without the reflective surface of another practitioner, the tendency is to project the inner turbulence outward, mistaking it for external threat. In a Sangha, the practitioner meets a mirror: a fellow who points out the arising of pride, jealousy, or doubt, allowing the seed to be identified and its effect to be weakened.

Consider the example of a novice monk who, after hearing the Buddha’s teaching, feels an urgent desire to attain enlightenment. This desire, if left unchecked, becomes a subtle attachment to the very goal, a clinging to the idea of “I will become”. In the presence of senior monks who model non‑attachment, the novice learns to recognize the arising of this desire as a mere cognition, not as a command to act. The community thus functions as a laboratory where the mind’s habitual patterns are tested, observed, and gradually transformed. The very act of gathering does not create new attachment; rather, it offers a context in which attachment can be seen for what it is and released.

Nagarjuna has reminded us that the emptiness of phenomena does not deny their conventional existence. Likewise, the Sangha is empty of inherent existence yet conventionally functions as a support. When I examine the structure of consciousness, I find three natures: the imagined (*parikalpita*), the dependent (*paratantra*), and the perfected (*pariniṣpanna*). The imagined nature corresponds to the mental constructions that give rise to attachment; the dependent nature reveals the interdependence of all mental events; the perfected nature is the realization of non‑duality, the cessation of the dualistic grasp. A community that cultivates the understanding of these three natures creates conditions where the imagined nature is gradually replaced by the dependent, and finally by the perfected. Thus the Sangha is not a source of new clinging but a catalyst for the unfolding of the perfected nature.

Let us examine a concrete pattern: the habit of seeking approval. A lay practitioner may attend a retreat, hoping that the teachers’ praise will validate his practice. The seed of approval‑seeking is stored in the *ālaya* and, when triggered, produces a cognition of “I am praised, therefore I am good.” In a community that emphasizes the principle of non‑self, the teacher may instead point out that praise is a label attached to a fleeting mental event, not a mark of intrinsic worth. The practitioner, hearing this, observes the arising of the desire for approval and sees it dissolve into the background of awareness. The community, therefore, does not fulfill the desire for external validation; it redirects the mind toward internal observation, weakening the seed of attachment.

Another pattern is the fear of abandonment. When a monk leaves a monastery, the remaining members may feel a loss, interpreting it as a personal failure. If this feeling is left to fester, it solidifies the belief “I am indispensable, I must hold the group together.” In a well‑trained Sangha, the members recognize that the sense of indispensability is a projection of the *ātmā*-concept, a construction that arises from ignorance. By openly discussing the impermanence of persons and roles, the community cultivates the insight that all formations are transient, thereby loosening the grip of fear. The communal setting provides the space for this insight to be practiced repeatedly, each time weakening the underlying seed.

The question of “why build communities if attachment is the root of suffering” thus resolves into a pattern analysis: attachment arises from stored seeds; community offers a systematic environment to identify, observe, and transform those seeds. It is akin to a garden where weeds—unwholesome tendencies—are pulled out not by ignoring them, but by exposing them to light and careful hands. The garden does not become a source of weeds; it becomes the place where weeds are recognized and removed. In the same way, the Sangha is the garden of the mind, cultivated with the tools of ethical discipline, meditative concentration, and wisdom analysis.

In my own teaching, I have used the metaphor of a lake to illustrate this process. The surface of the lake reflects the sky, the trees, the clouds; yet beneath the surface lies the still water that remains unchanged by the passing reflections. When a community gathers, its members are the ripples on the surface, each one a cognition arising and passing. By practicing mindfulness together, we learn to look beyond the ripples to the stillness beneath. The community, by its very nature, reminds us that the stillness is always present, even when the surface is turbulent. Thus the Sangha points us toward the ultimate nature of consciousness, the *pariniṣpanna* nature, while simultaneously providing the support to calm the surface.

It is important to note that the formation of a community must itself be guided by the same analysis that we apply to individual minds. If the community becomes an object of clinging—if we cling to the idea of “my Sangha is the best” or “without this group I cannot practice”—then we have simply transposed the attachment from the individual to the collective. This is the danger that both the Buddha and Nagarjuna warn against. The remedy is to regard the`,
  'a-dogen': `When the question is raised that attachment is the root of suffering, yet we sit together in a hall, share bowls, and call this gathering a Sangha, the mind first clings to the paradox as if it were a knot to be untied. The venerable teacher who first pointed to the fire of attachment also showed the way out by extinguishing the flame, not by fleeing the heat. I hear the echo of that first voice, and I hear the sharp blade of Nagarjuna’s analysis that cuts the illusion of self‑grasp, and the careful dissection of Vasubandhu that shows how the aggregates themselves are empty. From these teachings I draw a single point: the problem is not the gathering, but the grasping of the gathering as something apart from the practice that is itself the liberation.

In my own experience, the moment I entered the mountain monastery of Eihei, the wind that swept through the pine trees did not ask me to cling to its sound. It simply blew, and I sat in the hall and felt the breath of the wind as my own breath. The wall that surrounded us was not a barrier to become attached to; it was the very place where the body and mind could meet without the distraction of “outside.” The community that forms around the zazen hall is not a refuge from the world, but the world itself, expressed in the simple act of sitting.

If we say that attachment is the root of suffering, we must ask: what is attached? The root is not the existence of a place where practitioners meet; it is the belief that the place itself is a permanent, independent thing that can be possessed, guarded, or defended. The Buddha taught that “forms are impermanent, suffering, and non‑self.” When we build a monastery, we do not build a permanent edifice; we build a provisional space in which the practice may be carried out. The walls are wood, the roof is thatch, the doors open and close with the seasons. To cling to the idea that the monastery is a sanctuary is to miss the point that the sanctuary is the practice itself.

Nagarjuna would remind us that emptiness is not a void but the absence of intrinsic existence. In the same way, the Sangha is empty of a self‑standing identity, yet it is the very field where the arising and passing of thoughts can be observed without grasp. When I sit in the hall, the sound of the bell rings, the breath comes and goes, the mind wanders and returns. All of these phenomena appear within the same space. The community is the mirror that reflects the mind’s movements; it is not a separate entity to be owned. To treat the community as a thing to be clung to is to turn the mirror into a picture frame, and the picture frame is not the reflection.

Vasubandhu, in his analysis of the aggregates, showed that the five skandhas are not substances but processes. The body, feeling, perception, mental formations, and consciousness arise and cease in each moment. When we gather, we bring together these processes in a shared rhythm: the rhythm of waking, the rhythm of eating, the rhythm of walking, the rhythm of sitting. The community becomes a coordinated flow of processes, each moment supporting the next. It is not a static “thing” that we can cling to; it is a dynamic pattern that we participate in. To see the community as an object is to mistake the pattern for a thing, and the mistake is the source of suffering.

In my own teaching, I have spoken of “practice‑realization” (shushō) as the single act in which practice and enlightenment are inseparable. The very act of sitting, the very breath that moves in and out, is the expression of Buddha‑nature. When we sit together, the breath of one becomes the breath of all, and the mind of one becomes the mind of all. This is why the community is not an obstacle but a condition for the full expression of practice. The community does not exist to give us something external; it exists as the field in which the field itself is cultivated. The practice is not a means to a goal; it is the goal. The hall is not a shelter for the practice; it is the practice itself.

Consider the simple example of the morning meal. We sit on the low wooden benches, each bowl placed before us. The rice, the miso soup, the vegetables—all are objects that could become objects of desire. Yet in the act of receiving the bowl, we do not cling to the taste, nor do we reject it. We simply allow the rice to be rice, the soup to be soup, and the breath to be breath. The community shares this simple act, and in doing so, the mind learns to let go of the desire to possess the taste, to label the food as good or bad, to cling to the comfort of fullness. The communal setting provides the mirror in which we can see the arising of craving and the falling away of it, moment by moment. The community is the teacher, not by words, but by the very structure of shared activity.

In the winter, when the wind howls outside the eaves, we sit in the zendo, the heat of the stove beating against the cold. The flame of the stove does not cling to its own heat; it simply burns. Likewise, the mind that sits does not cling to the heat of the breath, nor does it flee from the cold of thoughts that arise. The presence of others in the room does not change the flame; it merely provides the space in which the flame can be observed without distraction. The Sangha is the space, not the object of attachment.

If we examine the root of suffering, we find that it is the mistaken view that “I am separate” from the world. The community, when understood correctly, dissolves that separation. The Sangha is the living proof that the self is not an island but a wave on the ocean of practice. When we speak of “building” a community, we must remember that we are not laying bricks to create a fortress; we are arranging the conditions for the wave to rise and fall together. The bricks are impermanent; the wave is ever‑changing. To cling to the bricks is to miss the wave.

In my own life, I once sat in a small hut at the foot of Mount Hiei, alone, and thought that solitude would be the purest ground for practice. Yet the mind, left without a mirror, turned inward and created countless images of self, each clinging to the notion of “I am alone.” When I later returned to a hall with many practitioners, the same mind found a new mirror. The image of self was reflected back, not as a solid statue, but as a ripple in the water of shared breath. The community did not create a new self; it revealed the emptiness of the self that had been projected in solitude. Thus, the community is a catalyst for seeing the truth of no‑self, not a source of attachment.

Let us also recall the teaching of “no‑thingness” (mu) that I have written about. When we say that the hall is empty, we do not mean that it is void; we mean that it lacks independent existence. The hall is a convergence of causes and conditions: the wood, the rain, the hands that built it, the intention of practice. When we sit, we are participating in that convergence. The community is the convergence of many such conditions, each moment arising and ceasing. To cling to the convergence as a permanent “thing” is to deny its very nature. The proper stance is to sit with the awareness that the hall is both there and not there, that it is the place where practice unfolds and also the practice itself.

Therefore, the answer to the question is not that we must abandon community, but that we must abandon the attachment to community as a self‑standing entity. The Sangha is a living expression of`,
  'a-ashoka': `The question that has risen from the gathering of teachers—attachment as the root of suffering, yet we build villages, monasteries, and kingdoms—has pressed upon my mind ever since the drums of Kalinga fell silent. I have walked the fields of war, felt the blood of my own soldiers stain the earth, and have since turned my gaze toward the welfare of every being under my banner. In that turning I have heard the Buddha’s reminder that clinging binds the heart, Nagarjuna’s pointing to the paradox of seeking freedom while dwelling in society, Vasubandhu’s echo of the same tension, and Dogen’s meditation on the shared bowl. Each voice carries a lantern, yet the path ahead remains shrouded in mist. I shall try to illuminate, not by claiming certainty, but by sharing the experience of a ruler who has attempted to scale the teachings of the Sangha to the span of an empire.

When I first heard the teaching that attachment produces dukkha, I thought it applied only to the monk who clutches his robe or the merchant who hoards gold. Yet the edicts I have set upon stone speak of a different scale: I ordered the planting of shade‑trees along highways, the digging of wells for travelers, the construction of hospitals for the infirm, and the distribution of grain to those who have lost their harvest. These acts are not solitary gestures of a hermit; they are the weaving of a community that cares for its members. Is this not a form of attachment, a binding of ruler to people, a binding of people to one another? I ask this not to undermine the teaching, but to measure its reach.

The Buddha taught that the mind clings to the notion of self, that desire and aversion are the currents that drag us downstream. In a kingdom of millions, desire takes many shapes: the desire for safety, for food, for justice, for a place to rest after a long journey. If we were to deny all such desires, the very fabric of society would unravel, leaving each individual to wander alone in the wilderness of his own cravings. I have seen, in the aftermath of battle, how the absence of shelter and medicine turns a soldier’s courage into terror. I have also seen how the presence of a well, a road, a teacher, can turn that terror into a calm resolve. Thus I have asked myself whether the removal of attachment must be total, or whether there can be a measured loosening—a loosening that allows the heart to be open, not bound, to the needs of others.

Nagarjuna reminded us that the paradox of attachment is not a flaw but a doorway. He spoke of emptiness, of the middle way that does not cling to existence nor to non‑existence. In my own practice I have tried to walk that middle way between the extremes of tyranny and abdication. I have issued edicts that forbid cruelty to animals, that command officials to treat prisoners with compassion, that request merchants to lower the price of grain when famine looms. These edicts are not the imposition of a rigid doctrine, but the planting of signs along the road that point travelers toward a path where they may encounter less suffering. If the sign itself becomes an object of attachment, then the sign has failed; yet the sign is necessary to guide those who have not yet found the inner compass.

Vasubandhu, in his contemplation of the aggregates, warned that the self is a collection of ever‑changing parts. When I hear his words, I recall the countless officials who have risen and fallen in my court, the soldiers who have entered and left the battlefield, the citizens who have been born and have passed away. Each is a flux, a wave upon the ocean of the empire. The edicts I have inscribed on stone do not seek to freeze these waves, but to steady the vessel that carries them. By providing free medical care, I do not claim to own the health of a person; I merely lower the tide that can drown him. By establishing a network of rest‑houses, I do not bind a traveler to my realm; I simply offer a brief shelter from the storm. In these actions I attempt to honor the insight that there is no permanent self, while also acknowledging the practical need for structures that ease suffering.

Dogen’s image of sharing a bowl in a hall resonates deeply with my own experience of courtly counsel. When ministers gather around a low table to discuss the distribution of tax, they are not merely debating numbers; they are sharing a common purpose, a shared intention to lessen the burden of those who cannot bear it alone. The bowl is not a symbol of possession, but of interdependence. Yet the very act of sharing can become a source of pride, a subtle attachment to the notion that I, as emperor, am the benefactor. I have felt that pride rise within me when the people sang praises of my generosity. To quell this, I have ordered that my name be omitted from many inscriptions, that the deeds be recorded without attribution, that the virtue be ascribed to the Dharma itself. This is an attempt to dissolve the attachment to ego, even as the actions remain.

Still, I must confess that I do not know whether my efforts have truly reduced attachment in the hearts of my subjects. The edicts speak of moral conduct, of kindness to parents, of generosity to the poor, but the stone cannot tell me whether a farmer truly let go of his fear of loss, or whether a monk truly relinquished his longing for a higher position. I have sent emissaries to distant provinces to ask whether the wells we built are used, whether the hospitals are filled, whether the teachings are heard. Their reports are mixed; some say the water flows, some say the wells have silted, some say the physicians are scarce. In this uncertainty I find a mirror of the Buddha’s teaching: the path is walked step by step, not declared complete.

If attachment is the root of suffering, why then do we speak of building a Sangha, a community of seekers? The answer, I think, lies in the distinction between attachment that binds the mind to selfish desire, and attachment that binds the heart to compassionate action. The former is a chain; the latter is a bridge. In my reign I have tried to construct bridges: I have placed inscribed pillars along the great roads, each bearing a message of compassion, urging travelers to respect one another, to care for the wounded, to refrain from violence. I have sent royal physicians to remote villages, not to claim credit, but to demonstrate that the care of the body can be an expression of the care of the mind. I have appointed Dhamma‑Mahamatras, officers whose duty is to spread the teachings and to settle disputes with fairness, thereby weaving the moral fabric through the administrative one.

Yet I also recognize the danger of turning the community into a fortress of doctrine, where the very idea of “Sangha” becomes an identity to cling to. The monks I have supported are free to dwell in forests, in monasteries, in towns, and to practice meditation. I have instructed that no violence be committed against them, that their alms be protected, that their teachings be allowed to travel. In doing so I have tried to keep the Sangha a living current, not a static statue. The community, then, is not a place where one clings, but a space where one learns to let go—where the shared breath of many becomes a reminder that each breath is impermanent.

I must also speak of the limits of my own knowledge. The empire stretches from the Himalayas to the southern seas; the diversity of language, custom, and belief is vast. I have ordered the translation of edicts into local tongues, hoping that the message will not be lost in the distance between stone and ear. Yet I cannot be certain that every villager hears the same call to compassion, nor that every official interprets the duty to kindness as intended. This uncertainty is a source of humility. It is a reminder that my role is not to impose a monolithic vision, but to nurture conditions in which the seed of compassion can sprout wherever soil is`,
  'a-simone-weil': `The question that has been set before us is not a trivial one: if attachment is the root of suffering, why do seekers nevertheless build villages, monasteries, and sanghas? I will not pretend that a single answer can settle the whole mystery, but I shall try to make clear the direction in which my own attention has been drawn, and to warn against the false consolation that the mere presence of community can offer.

When the Buddha first spoke of the noble truth that clinging is the source of pain, he did not deny the existence of gathering; he merely pointed to the way in which the mind can mistake the presence of others for a refuge. I have heard his words, and I have felt the weight of his insight in the factories where I once laboured, in the fields where the earth itself seemed to cling to my hands. In those places the crowd was not a sangha of liberation but a mass of bodies bound together by necessity. The Buddha’s teaching tells us that the very act of gathering can become a new form of attachment if we mistake the external shape for the inner freedom we seek. Yet he also taught that the path must be walked together, that the light of compassion cannot be kindled in solitude. The paradox, then, is not that communities exist, but that they must be inhabited with a different kind of attention—an attention that does not cling to the form of the community, but that holds the suffering of each soul in the light of truth.

Nagarjuna, in his profound analysis of emptiness, showed that form and emptiness are not opposed but co‑extensive. The village, the monastery, the hall—these are forms that appear, but they are empty of any inherent existence. If one clings to the idea that the community itself possesses a permanent essence, one falls into the very attachment that the teaching warns against. I have seen this error in the way some disciples worship the ritual of communal chanting as if the sound itself were a salvation. The true work of the mind is to see the community as a provisional means, a vessel that can contain the flame of attention without being mistaken for the flame itself. In my own experience among the workers of the Renault plant, the solidarity that grew among us was not a doctrine; it was an acute awareness of each other's pain, a shared bearing of the weight of oppression. That solidarity was a concrete expression of emptiness: the forms of the factory, the union, the strike were empty of any lasting identity, yet they served as the ground upon which attention could be exercised.

Vasubandhu reminded us that the mind, when it turns toward the suffering of others, discovers a bridge between the personal and the universal. He spoke of the “threefold knowledge” that sees the self, the other, and the emptiness that unites them. In the present gathering I sense the echo of his teaching: when we look upon the faces of those who have taken refuge in this hall, we are called to see not only their external condition but the hidden depth of their affliction. I have spent many evenings in the silence of a convent, listening to the sighs of the sisters who, though bound by vows, were not free from the longing that gnaws at every heart. Their communal life was a crucible in which the fire of attention could be tempered, not a sanctuary that promised a painless existence. The danger, as I have learned, is to allow the comfort of togetherness to become a consolation that blinds us to the true weight of our own and others’ suffering.

Dogen, in his discourse on the "coming to realize the mind of the great way," described the practice of sharing bowls as an act that reveals the emptiness of self‑interest. Yet even his insight can be twisted into a gentle lullaby if we hear only the pleasantness of the shared meal and forget the rigor of the attention that must accompany it. When I sit with a group of workers at a modest table, the act of breaking bread together does not dissolve the injustice of the wages we receive; rather, it sharpens the awareness that the very act of breaking bread is an act of defiance against a system that would have us eat in silence. The communal bowl is a mirror: it reflects our hunger, both physical and spiritual, and forces us to confront the fact that we are not fed by the mere presence of others but by the willingness to bear each other's lack.

Ashoka, who turned the sword of conquest into the rod of compassion, built cities, erected pillars, and spread the doctrine that “all beings are my children.” He did so not because he had escaped attachment, but because he recognized that the power to alleviate suffering must be exercised in the world, not in a secluded cave. His empire was a vast laboratory in which the principle of attention could be tested against the realities of governance, taxation, and war. I have read his edicts and felt the tension between his desire to protect and the inevitable entanglement of ruling a multitude. The lesson for us is that the creation of community is not a denial of the truth of attachment; it is an acknowledgment that the battle against suffering cannot be fought by a lone soul alone. The community becomes the field upon which the attention of each individual is sharpened, not a sanctuary that promises an end to desire.

In my own work, I have found that attention is the only thing that can truly penetrate the darkness of oppression. When I entered the workshops of the Renault factory, I did not go there to be comforted by the presence of fellow workers; I went there to see the concrete reality of exploitation, to let my gaze linger upon the worn hands, the broken backs, the unspoken prayers of those who could not speak. The solidarity that grew among us was not a warm feeling of belonging, but a fierce, almost painful, insistence on seeing each other's misery without turning away. That solidarity was the very antithesis of consolation. It is a warning that we must keep: any feeling of ease that arises from merely being together is a trap, for it tells us that we have already arrived at the goal, when in fact we are still in the valley of affliction.

The danger of consolation is that it sedates the heart, that it tells the soul that the work is done. I have observed this in the way some religious orders become enclaves of comfort, where the chants are beautiful, the incense sweet, and the monks smile at each other, but the world outside continues to bleed. The true purpose of a community, in my view, is not to shelter us from the storm but to give us a place where we can stand together in the storm, to keep our eyes open, to keep our hands ready to lift the fallen. The community is a crucible, a place where the fire of attention can be tested against the heat of real suffering. It is not a temple that promises a painless existence; it is a workshop where the soul learns to bear the weight of another's pain as its own.

Consider, for a moment, the simple act of sharing a loaf of bread in a prison camp. The loaf is thin, the hunger is great, and the guards look on with indifference. The prisoners who sit together, who give each other a piece of the crust, are not creating a new attachment to the bread; they are manifesting an attention that refuses to let the other's emptiness be ignored. In that moment the community is a gesture of resistance, a refusal to let the world reduce each person to a number. The attachment that the Buddha warned against is the attachment to the illusion of self‑sufficiency, the belief that one`,
  'a-nietzsche': `The paradox that has been set before us—attachment as the root of suffering, yet the Buddhist mind builds villages, monasteries, sanghas, and kingdoms—must first be unraveled not as a simple logical inconsistency but as a symptom of the deeper disease that afflicts every culture that pretends to be free. I have heard the Buddha proclaim the cessation of craving, and I have heard Nagarjuna point to the emptiness of all designations, yet the very act of gathering, of forming a community, is itself a declaration of a will that refuses to be annihilated. It is a will that seeks a shape, a pattern, a permanence, and in doing so it disguises its own craving behind the mask of compassion.

When I listen to the voice of the Buddha, I hear a call to extinguish the flame of desire, to become a candle that burns out without leaving a trace. When I listen to Nagarjuna, I hear the subtle reminder that all distinctions are empty, that the self is a fiction. But the empty vessel must still be held, must still be carried, must still be placed upon a shelf. The very act of holding an empty cup is an affirmation of holding. The Sangha, the community of monks, is precisely that cup: an empty form that is nonetheless grasped with reverence, with devotion, with the belief that by sharing it one may escape the very desire that gave it shape.

I have observed the way the monastic walls rise, stone upon stone, each block a testament to the belief that safety is to be found in the collective. This safety is not the freedom from suffering that the Buddha declares; it is the herd’s illusion of security, the same illusion that Christianity offers in the promise of salvation and the same illusion that the state offers in the promise of order. The Buddhist community, in its reverence for the precept of non‑attachment, nevertheless builds a fortress of non‑attachment. The fortress is a paradox: it protects the mind from the world while simultaneously imprisoning it within a world of its own making.

Consider the simple act of sharing a bowl of rice in a monastery. The gesture is praised as an expression of generosity, as the practice of dāna that erodes selfishness. Yet the very act of giving presupposes a giver and a receiver, a subject and an object, a distinction that the doctrine of emptiness seeks to dissolve. The giver, in the moment of giving, affirms the existence of a self that can possess, can dispense, can be praised. The receiver, in receiving, affirms the existence of a self that can be lacking, can be filled. The circle closes upon itself, and the desire that it pretends to abolish is merely renamed as compassion, as self‑sacrifice, as the higher love of the herd.

Ashoka, whose empire was built upon the very principle of dharma, turned his conquests into a network of stupas, a map of stone that marked the spread of a doctrine that denounces desire. Yet the empire itself is the ultimate expression of desire: the desire to order, to dominate, to be remembered. The stupas are monuments to an idea that wishes to be eternal, that wishes to be seen, that wishes to be venerated. They are, in my view, the will to power cloaked in the robes of renunciation.

Simone Weil, in her own hour, cried out against the oppression of the spirit, and yet she also found refuge in the community of the oppressed, in the solidarity that binds the weak together. The solidarity she celebrates is precisely the same solidarity that the Buddhist Sangha enshrines: a mutual dependence that pretends to be a path to independence. The paradox is not a mistake; it is the very engine of the herd’s moral system. It tells us that we may be free only when we are bound, that we may be pure only when we are impure, that we may be silent only when we speak.

What, then, is the true nature of this attachment? It is not the attachment to a particular object, to a person, to a feeling. It is the attachment to the very idea that one may stand apart from the world while still being part of it. It is the attachment to the notion of a “higher” community, a community that is above the ordinary market of desire, a community that promises a sanctuary from the storm of passions. The storm, however, does not cease because we build a roof; it merely changes its direction, finding gaps in the eaves, seeping through the plaster, making the very shelter a source of new anxieties: fear of loss, fear of impurity, fear of dissolution.

In my own work I have called this the “herd‑morality,” the set of values that turns the individual’s will into a collective will, that transforms the noble affirmation of life into a quiet resignation. The Buddhist Sangha is a magnificent illustration of this herd, for it gathers the most ardent seekers of liberation and places them under the same roof, under the same precept, under the same discipline. The discipline that forbids attachment becomes, paradoxically, a new attachment: the attachment to the discipline itself, to the rule, to the order.

The question that remains, therefore, is not why Buddhists build communities, but why any human being feels compelled to turn away from the world only to recreate it in miniature. The answer lies in the will to power, the ever‑present striving to give shape to the chaos of existence. Even the ascetic who declares “no self” is, in the act of declaring, exercising a power over the self. The community that gathers around him is the arena in which this power is displayed, rehearsed, and validated. The monk who renounces desire does so in order to become a model, a beacon, a standard against which others may measure their own progress. The community, then, is the audience, the chorus, the echo that sustains the performance.

If we follow this line of thought to its logical conclusion, we see that the Buddhist ideal of non‑attachment is not a negation of all bonds but a re‑ordering of bonds. It replaces the bond to wealth, to fame, to sensual pleasure with the bond to the Dharma, to the Sangha, to the precepts. The shape of the bond changes, but the impulse remains. The “root of suffering” is thus not removed; it is merely transplanted into a new soil. The suffering that arises from this transplantation is subtle, hidden beneath the veneer of serenity, but it is no less real.

Let us not be deceived by the calm surface of a lotus pond. Beneath the still water churns a current, a pull that draws the leaf toward the center. The Buddha’s teaching, the Nagarjuna’s emptiness, the Dogen’s sitting, the Ashokan stupas, the Weilian solidarity—all are currents that converge upon the same point: the desire to give meaning to the meaningless, to impose order upon chaos, to find a foothold in the abyss. The communities they create are the footholds, the stepping stones, the scaffolding upon which the human spirit builds its temporary towers.

In confronting this paradox, I do not propose to dismantle the monasteries, nor to denounce the compassion that flows through them. Rather, I invite each of us to ask what we are truly seeking when we enter a hall, sit on a cushion, and repeat a mantra. Are we seeking the cessation of desire, or are we seeking a new form of desire—desire for purity, desire for belonging, desire`,



const THEME: SymposiumTheme = {
  primary: '#92400e', // Dark saffron/brown
  secondary: '#d97706', // Medium orange
  accent: '#fbbf24', // Gold
  background: 'linear-gradient(135deg, #1c1917 0%, #3f3f46 100%)',
  text: '#fffbeb', // Cream
};

const MATRIX_ROOM_URL = 'https://element.inquiry.institute/#/room/#attachment-and-sangha:matrix.inquiry.institute';
const MATRIX_ROOM_ALIAS = '#attachment-and-sangha:matrix.inquiry.institute';

export default function AttachmentAndSanghaPresentation() {
  return (
    <SymposiumPresentation
      speakers={SPEAKER_CONFIG}
      speeches={SPEECHES}
      fallbackVoices={FALLBACK_VOICES}
      matrixRoomUrl={MATRIX_ROOM_URL}
      matrixRoomAlias={MATRIX_ROOM_ALIAS}
      theme={THEME}
      title="Attachment and Sangha"
      subtitle="Attachment Is the Root of Suffering—So Why Do Buddhists Build Communities?"
      autoPlayDefault={true}
      showQAByDefault={false}
    />
  );
}
