/**
 * Attachment and Sangha Symposium Presentation
 * Wrapper component that configures the generic SymposiumPresentation
 */

import SymposiumPresentation, {
  type SpeakerConfig,
  type FallbackVoice,
  type SymposiumTheme,
} from './SymposiumPresentation';

const SPEAKER_CONFIG: SpeakerConfig[] = [
  { id: 'a-gautama-buddha', name: 'Gautama Buddha', epithet: 'Founder of the Sangha' },
  { id: 'a-nagarjuna', name: 'Nāgārjuna', epithet: 'Philosopher of Emptiness' },
  { id: 'a-vasubandhu', name: 'Vasubandhu', epithet: 'Psychologist of Mind' },
  { id: 'a-dogen', name: 'Dōgen', epithet: 'Practice Radical' },
  { id: 'a-ashoka', name: 'Ashoka', epithet: 'Political Realist' },
  { id: 'a-simone-weil', name: 'Simone Weil', epithet: 'Severe Mystic' },
  { id: 'a-nietzsche', name: 'Friedrich Nietzsche', epithet: 'The Prosecutor', isHeretic: true },
];

const FALLBACK_VOICES: Record<string, FallbackVoice> = {
  'a-gautama-buddha': { voice: 'en-IN-PrabhatNeural', rate: 0.95, language: 'en-IN', accent: 'Indian English, multilingual' },
  'a-nagarjuna': { voice: 'en-IN-PrabhatNeural', rate: 0.96, language: 'en-IN', accent: 'Indian English, analytical, precise' },
  'a-vasubandhu': { voice: 'en-IN-PrabhatNeural', rate: 0.97, language: 'en-IN', accent: 'Indian English, cognitive, systematic' },
  'a-dogen': { voice: 'ja-JP-KeitaNeural', rate: 0.94, language: 'ja-JP', accent: 'Japanese, direct, uncompromising' },
  'a-ashoka': { voice: 'en-IN-PrabhatNeural', rate: 0.95, language: 'en-IN', accent: 'Indian English, regal, reflective, weighty' },
  'a-simone-weil': { voice: 'fr-FR-DeniseNeural', rate: 0.96, language: 'fr-FR', accent: 'French, intense, severe, mystical' },
  'a-nietzsche': { voice: 'de-DE-KatjaNeural', rate: 0.98, language: 'de-DE', accent: 'German, provocative, challenging, intense' },
};

// Generated speeches using ask-faculty edge function
// Target length: ~1050 words per speech (~7 minutes at 150 wpm)
const SPEECHES: Record<string, string> = {
  'a-gautama-buddha': `The mind, like a river that rushes past many banks, often believes that what it clings to is the source of its safety. In hearing the words of those who have spoken before me, I recall the clear exposition of the Four Noble Truths: suffering arises, its cause is craving, its cessation is possible, and the path leads beyond. Yet a question has arisen: if attachment is the very root of suffering, why do we, who have taken refuge in the Dharma, gather together, build monasteries, form a Sangha, and share in common meals and rituals? Does the act of forming a community not itself become a new attachment, a new source of craving?

To answer, let us first examine the nature of attachment. Craving, as I taught, is not merely the desire for a particular object, but the subtle conviction that one cannot be whole without that object. It is the belief that the self is complete only when it possesses, when it is praised, when it is defended against loss. When a person clings to a precious jewel, the jewel is not the problem; it is the belief that the jewel defines the worth of the self. The same holds for ideas, for status, for even for the very notion of “community.” If one holds the community as a source of identity, as a fortress against the world, then the gathering becomes a new chain.

But the Sangha, as it was ordained by the Buddha, is not intended to be a shelter of identity. It is a field of practice, a place where the foot‑paths of the Noble Eightfold Path are walked together, not for the purpose of gaining belonging, but for the purpose of supporting the removal of the very attachment that binds us. The Buddha said, “Just as a great fire is quelled by a single drop of water, so too does a single wholesome mind quiet the blaze of craving.” In a solitary forest, the drop may fall unnoticed; in a cultivated garden, many drops gather, each reinforcing the other's cooling effect. The community, therefore, is a means, not an end.

Consider the parable of the reeds that grow by the riverbank. A single reed, bent by the wind, may snap. Yet a thicket of reeds, rooted together, bends as one and withstands the storm. The Sangha is like that thicket. Each practitioner, like a reed, is vulnerable to the gusts of desire, aversion, and ignorance. When they stand together, they remind one another of the breath, of the impermanence of thoughts, of the need to observe sensations without grasping. The community does not become an object of attachment because its purpose is defined by non‑attachment: it is a space for mindful observation, for the sharing of insight, for the mutual encouragement to let go.

In the early days after my enlightenment, I gathered five companions who had also abandoned the life of a householder. We sat together under the tree of the moon, and each of us examined the arising of feeling, the arising of thought, the arising of intention. When one faltered, the others offered a word of encouragement, not as a promise of salvation, but as a reminder of the path. This is the practical outcome of a community: it provides the conditions in which the mind can see clearly, unclouded by the delusion that it must stand alone. The Dhamma is not a solitary fire that one must keep alone; it is a lamp that can be passed from hand to hand, brightening the darkness for all.

Now, let us turn to the middle way, that path which avoids the extremes of self‑indulgence and self‑mortification. If one were to reject all forms of gathering, to live in complete isolation, one would fall into the extreme of self‑denial, believing that any reliance on another is a source of attachment. Yet extreme seclusion also breeds the mind’s tendency to invent its own attachments: the attachment to solitude, the attachment to personal austerity, the attachment to the idea of being “above” the world. The middle way therefore permits association, but only when the association is understood as a support for practice, not as a source of identity.

A concrete example may illustrate this balance. A monk who lives in a forest hermitage may find great peace, but when the mind stirs with doubt—“Am I truly on the path?”—the lack of a companion to ask, “What have you observed of the breath?” may allow the doubt to become a seed of craving for certainty. In a monastery, another monk can ask, “What is the nature of the feeling that arises when you think of the past?” The dialogue itself does not create attachment; it creates an occasion for direct experience to be examined. The community, then, is a mirror in which each practitioner can see the reflections of his own mind, without being trapped by the image.

It is also essential to recognize that the Sangha is not a monolithic entity that demands uniform belief. The Buddha taught that the true measure of a community is not its size, nor its wealth, but the purity of its conduct: “Those who abide in virtue, who live in harmony, who have compassion for all beings, are the true Sangha.” When the community is built upon ethical conduct—right speech, right action, right livelihood—it becomes a living embodiment of the path. Ethical conduct itself is a practice of non‑attachment: it is the refusal to grasp at harmful actions, the refusal to cling to pleasures that cause suffering. By living together in accordance with these precepts, members reinforce each other's resolve to let go.

There are those who point to the rituals, the chanting, the offering of alms, and claim that these are mere forms of attachment to tradition. Yet each of these actions, when performed with mindfulness, is a vehicle for insight. When a monk receives alms, he does not cling to the food as a treasure; he uses it as a reminder of impermanence: the taste will fade, the body will digest, and the nourishment will be used to sustain the practice of meditation. When a layperson offers incense, the offering is not an attempt to accrue merit for future gain, but a moment of generosity that opens the heart, loosening the grip of selfish desire. The form is a skillful means, a raft to cross the river of ignorance; the attachment would be to cling to the raft as if it were the shore.

Thus, the building of monasteries, the sharing of robes, the collective recitation of the Dhamma—these are all expressions of the principle that the path is best walked in concert, not in isolation. The Buddha himself said, “Just as a single candle can be extinguished by a gust, a thousand candles together can illuminate the world.” The community is the thousand candles, each flame sustained by the others, each flame aware that its light is temporary, and each flame offering its light without demanding reverence.

In practice, the Sangha provides three essential supports: moral support, intellectual support, and the environment for meditation. Moral support arises when a practitioner witnesses another’s effort to keep the precepts, reminding him of the value of restraint. Intellectual support appears when a monk asks a question about the nature of dukkha, and another offers a clarification drawn from personal observation. The environment for meditation is created when a hall is kept quiet, when the schedule allows for regular sitting, when the space is free from distraction. All these supports are conditional, not absolute; they are offered because they are useful, not because they are cherished as ends in themselves.

When a layperson wonders whether the act of building a monastery binds him to a new form of attachment, the answer lies in the intention behind the building. If the intention is “I will be praised for constructing a great hall,” the act becomes a source of craving. If the intention is “I provide a shelter where seekers may practice the Dhamma,” the act becomes a skillful means, a selfless offering that does not cling to the result. The difference is subtle, but it is the difference between grasping and letting go.

The Buddha taught that the true nature of all phenomena is emptiness of self‑existence, that they arise dependent on causes and cease when those causes cease. The community, therefore, is not a permanent entity; it is a contingent gathering, arising because practitioners need support, and it will dissolve when the need no longer exists. Recognizing this impermanence prevents the community from becoming an object of attachment. When a monk sees the monastery as a temporary shelter, he can use its facilities without fearing loss when they change.

In concluding, let us recall the`,
  'a-nagarjuna': `The river that the Blessed One described flows ever onward, its waters touching many banks yet never clinging to any shore. In that image we hear the warning against grasping what is impermanent, for the mind that seeks a fixed point finds only turbulence. Yet the same river gathers together many streams, each joining without losing its character, forming a larger current that carries all toward the sea. This paradox—of non‑attachment and of gathering—mirrors the question now raised: if attachment is the root of suffering, why do practitioners assemble in sanghas, in monasteries, in the very communities that seem to affirm a bond?

To answer, we must first dissolve the binary that separates “attachment” from “association.” The doctrine of dependent origination teaches that all phenomena arise co‑dependently; nothing exists in isolation, nor does anything arise from a single cause. Emptiness, then, is not a void beyond all relation but the lack of inherent, self‑existent nature in any dharma. When a monk sits in a hall with others, the hall is not a self‑existent “community” that the mind can cling to as a source of safety. Rather, the hall is a web of causes and conditions: the intention of the teachers, the generosity of lay supporters, the climate that permits construction, the shared vows that sustain practice. Each element is empty of independent essence, yet together they give rise to a supportive environment for the path.

If we mistake this interdependent gathering for an inherent entity, we fall into the very attachment the Buddha warned against. The sangha, when understood as a fixed “self,” becomes a source of pride, of identity, of refuge. The mind then clings to the notion “I am a monk, I belong to this community,” and the suffering of self‑attachment reappears. The Middle Way therefore calls us to regard the community as a provisional aid, a conventional truth that functions without becoming an ultimate anchor. In the same way a boat is useful for crossing a river yet is not the river itself, the sangha is useful for crossing the ocean of samsara without being the shore we ultimately seek.

Consider the example of a novice who enters a monastery seeking refuge from the storm of desire. He finds teachers who point out the emptiness of the self, and he receives alms from laypeople who, in turn, gain merit by giving. The novice’s practice thrives precisely because of these conditions. Yet if he were to think, “My liberation depends on the monastery; without it I cannot be free,” he would create a subtle attachment to the very support that should be let go. The correct view is to see the monastery as a dependent origination: it arises because of causes, it functions because of conditions, and it ceases when those causes cease. The practitioner, aware of this, uses the setting as a skillful means, not as a permanent shelter.

The Buddha’s teaching on the “four noble truths” already hints at this balance. The truth of suffering points to the problem of grasping; the truth of the cause of suffering identifies craving; the truth of cessation shows that letting go ends the pain; and the truth of the path offers a method. The sangha belongs to the fourth truth: it is part of the eightfold path, specifically right effort, right mindfulness, and right concentration, all of which are cultivated most effectively in a communal setting. The path is not a solitary ascent of a lone wanderer but a collective ascent where each step is reinforced by the presence of companions who remind one of the middle way.

A further illustration comes from the story of the monk who, after years of solitary meditation, achieved a deep insight into emptiness but then fell into arrogance, proclaiming that he alone had realized the truth. His pride caused a rupture in his relationships, and his practice deteriorated. When he later returned to a community, he realized that the very presence of others—who, though empty of self, embodied compassion and patience—served as a mirror for his own delusion. The community did not grant him salvation; it merely reflected the truth he had already glimpsed, allowing him to correct his error. Thus, the sangha functions as a safeguard against the subtle re‑emergence of attachment, not as an object of attachment itself.

From a logical standpoint, we can formulate the argument as follows: Let C denote the condition of attachment, which yields suffering S. Let G denote the gathering of practitioners, which is a set of interdependent causes. If G were regarded as an inherent entity, then G would become a new source of C, reproducing S. However, if G is understood as empty, merely a conventional designation for a dependent network, then G does not generate C; rather, G provides the conditions under which the insight into emptiness can be cultivated, thereby reducing C and diminishing S. The syllogism is clear: the proper view of G prevents it from becoming a cause of suffering, while the improper view makes it a cause. Hence the community is compatible with the doctrine that attachment is the root of suffering, provided the correct understanding is maintained.

Some may argue that any form of organization inevitably creates hierarchy, rule, and identification, which are themselves sources of clinging. This objection is not without merit, and the Madhyamaka analysis does not deny the existence of such tendencies. What it does deny is the ultimate existence of the hierarchy as an independent, unchanging entity. The hierarchy is itself empty, a label applied to a pattern of interaction. When a monk recognizes that the title “abbot” lacks inherent nature, the respect owed to the position becomes a respectful acknowledgment of skillful conduct rather than a reverential attachment. The community can then function without the fetters of egoic grasping, because each member sees the roles as provisional, not as ultimate identity.

In practice, the cultivation of this insight requires a continuous examination of the conditions that give rise to attachment. When we sit in meditation and notice the feeling of “belonging” as a pleasant mental formation, we apply the analysis of emptiness: “Is this feeling a self‑existent object?” We discover that it is a composite of perception, memory, desire, and the surrounding environment. By seeing its emptiness, the feeling loses its grip, even as the supportive environment remains. The community therefore becomes the fertile soil in which the seed of wisdom can grow, while the fear that the soil itself might become a new idol is dispelled through the same analysis.

Therefore, the question of why Buddhists build communities, if attachment is the root of suffering, is resolved by recognizing the distinction between conventional and ultimate truth. The community is a conventional truth, a pragmatic arrangement of causes that eases the path toward ultimate insight. When we cling to the community as if it were the ultimate refuge, we fall back into suffering. When we understand its emptiness and employ it skillfully, we honor the Buddha’s teaching that the middle way avoids the extremes of self‑isolated asceticism and self‑indulgent attachment.

In closing, let us recall the river’s lesson once more. The river does not cling to any single stone, yet it gathers many stones into its flow, shaping its course. Likewise, the practitioner does not cling to the sangha as an ultimate haven, but lets the sangha gather the conditions necessary for the mind to recognize its own emptiness. The community, like the river, is a conduit, not a destination. By seeing it as empty of inherent self, we preserve the freedom that the Buddha proclaimed, and we allow the path to proceed without the fetters of attachment. May this understanding guide all who gather here, that they may use the communal support as a means, not as a means to an end, and thereby walk the middle way with clarity and compassion.`,
  'a-vasubandhu': `The mind, when examined as the stream of consciousness that flows in ever‑changing currents, reveals a pattern that is at once subtle and decisive: every wave of feeling, thought, or perception carries within it a seed of grasping, and that grasping is the hinge upon which suffering turns. The Blessed One taught that the river of mind rushes past many banks, clinging to each shore as if it were the source of safety. Nagarjuna later reminded us that the river never rests upon any bank, that its essence is empty of fixed attachment. From this shared imagery we may ask, then, why the sangha—our communal dwelling—should be erected at all if attachment is the very root of dukkha. To answer, we must first disentangle the two senses in which “attachment” operates: the internal fixing of the self‑view upon phenomena, and the external formation of supportive conditions that enable the mind to witness its own workings without further entanglement.

In the Abhidharma analysis I presented in the Treasury, consciousness is classified into thirty‑two distinct types, each arising from a specific sense‑basis and each accompanied by a corresponding mental factor. Among these factors the afflictive ones—rāga (attachment), dveṣa (aversion), and moha (delusion)—are the primary movers of the three poisons. When a visual object appears, the corresponding visual consciousness arises together with the factor of attachment, which grasps the image as “mine,” “pleasant,” or “desirable.” This grasping is not a mere intellectual assent; it is a rapid, automatic conditioning that colors the entire subsequent flow of mental events, leading to craving, clinging, and the endless cycle of birth and death. The eradication of this inner fixation is the direct path to liberation.

Yet the very analysis that isolates the afflictive factor also points to the conditions under which it can be observed, studied, and ultimately subdued. The mind does not operate in a vacuum; it is always situated within a field of causes and supports. The community of practitioners, the sangha, functions as a deliberately arranged set of conditions—ethical precepts, shared meditation practices, teachings, and mutual encouragement—that stabilise the mind sufficiently for the subtle workings of attachment to become visible. In other words, the sangha is not an object of attachment; it is a skillful means (upāya) that provides the fertile ground for the mind to recognise the very habit it must abandon.

Consider the analogy of a gardener tending a wild vine. The vine, left to its own devices, will grow tangled, obscuring the roots and choking the soil. The gardener does not cling to the vine as a prized possession; rather, he creates a trellis, trims the excess, and supplies water at measured intervals. In the same way, the sangha offers a trellis of ethical discipline (śīla) and a well‑sprung source of wisdom (prajñā). When a practitioner observes the precept of non‑harm, the immediate effect is the reduction of the mental factor of aversion; when the precept of truthful speech is upheld, the tendency toward deceit—another form of attachment to false self‑concepts—is weakened. These precepts are not ends in themselves; they are conditions that diminish the potency of the afflictive factors, allowing the practitioner to see the arising of attachment as a fleeting ripple rather than as a permanent shore.

The communal aspect also addresses a second, often overlooked, dimension of attachment: the mistaken belief that the self is an isolated island. The Yogācāra analysis of the eight consciousnesses, especially the ālayavijñāna (storehouse consciousness), shows that the sense of “I” is a construction arising from accumulated karmic imprints. When a practitioner works alone, the mind may reinforce the illusion of separateness, mistaking the solitary effort for self‑sufficiency. In a sangha, however, the mutual observation of conduct and shared reflection on doctrine expose this illusion. The simple act of hearing another’s confession of error, or offering a correction, creates a mirror in which the mind can recognise its own self‑referential patterns. This external mirroring does not constitute clinging to others; rather, it is the removal of the veil that hides the interdependent nature of consciousness.

To make this concrete, let us examine a familiar scenario from monastic life. A monk, after long hours of seated meditation, experiences a subtle feeling of pleasure—a lightness of body, a sense of ease. The mind, conditioned by past habit, may label this feeling as “good” and cling to it, hoping for its recurrence. In a solitary setting, the monk might be inclined to prolong the posture, seeking to retain the pleasant state, thereby reinforcing attachment. Within a community, the senior teacher observes the monk’s posture, offers a reminder of impermanence, and invites the monk to note the arising and passing of the feeling without grasping. The teacher’s guidance is not an external object of attachment; it is a catalyst that redirects the monk’s attention toward the impermanent nature of the experience, thereby weakening the attachment factor. The community, therefore, functions as a diagnostic tool, revealing the hidden currents of the mind that would otherwise go unnoticed.

Moreover, the sangha provides a safeguard against the subtle forms of attachment that arise when the practitioner becomes enamoured of the very practice itself. The Mahāyāna tradition warns of the “attachment to the path,” a subtle pride that can arise when one begins to see oneself as a superior seeker. This is precisely the kind of self‑referential clinging that the storehouse consciousness perpetuates. By establishing a structure in which all members are reminded of their own ignorance and the need for humility, the community prevents the mind from solidifying a new identity—“the diligent practitioner”—which would become another source of suffering. The communal vows, recited together, function as a collective reminder that even the aspiration to enlightenment is a provisional aid, not an ultimate possession.

Nagarjuna’s teaching on emptiness further clarifies why the community does not contradict the principle of non‑attachment. Emptiness (śūnyatā) is not a nihilistic denial of existence but the insight that all phenomena lack an inherent, independent nature. The sangha, when viewed through the lens of emptiness, is itself empty of self‑nature; it exists only in dependence upon the causes and conditions that give rise to it—namely, the shared aspiration for liberation and the ethical framework that sustains it. Recognising this, a practitioner does not cling to the sangha as a permanent refuge; rather, he uses it as a provisional support, aware that its existence is contingent and mutable. When the practitioner fully realises the emptiness of the community, the very fear of losing it dissolves, and the suffering born of that fear disappears.

From a methodological standpoint, the analysis of consciousness that I have presented in the Viṃśatikā and the Triṃśikā offers a systematic map for navigating these dynamics. The thirty‑two consciousnesses are not isolated; they flow in a sequence where the eight consciousnesses of the Yogācāra model give rise to the three natures (parikalpita, paratantra, and pariniṣpanna). The parikalpita nature—our conceptual overlay that fabricates the duality of self and other—is precisely where attachment takes root. The paratantra nature, the causal flow of mental events, can be observed and trained within the supportive environment of the sangha. When the practitioner, through meditation and study, recognises the pariniṣpanna nature—the ultimate non‑dual reality—attachment loses its power, because there is no longer a substantive self to cling to. The community, therefore, is a stepping stone along this path, a structured arena in which the mind can be trained to discern and abandon the parikalpita constructions.

Let us also reflect on the role of compassion (karuṇā) within this framework. Compassion is not merely an affective response; it is a cognitive re‑orientation that perceives the suffering of others as inseparable from one’s own. When a practitioner cultivates compassion within the sangha, the mind expands its field of awareness beyond the narrow confines of personal desire. This expansion weakens the grip of attachment, for the mind no longer fixes upon a singular object of gratification but opens to the welfare of all beings. The communal practice of sharing merit, of dedicating one’s own progress to the liberation of others, thus becomes an antidote to self‑centered clinging.

In sum, the`,
  'a-dogen': `The river of practice flows without striving toward a distant shore; it moves simply because the water is water. When the Blessed One taught that attachment is the root of suffering, he pointed not to the mere presence of caring, but to the clinging that turns caring into grasping. In the same way a fisherman who drags his net after every fish loses the joy of the river’s current, the mind that grasps the object of its affection loses the freedom of the present moment. Yet the teachings do not forbid the formation of a community, nor do they deny the value of building a place where the Dharma may be lived. The question, therefore, is not why we build a sangha, but how the building itself becomes the very expression of non‑attachment.

The Buddha’s metaphor of the river, as spoken by the first speaker, reminds us that the mind rushes past many banks, believing each bank to be a source of safety. This belief is a delusion: the banks are merely temporary contours, not the river itself. When a practitioner steps onto the bank and declares, “Here I will stay,” the river has already passed, leaving the mind stranded on a shore that is ever‑changing. The sangha, then, is not a bank upon which the practitioner clings, but a current in which the practitioner swims. The community is formed not by a desire to possess a fixed group, but by the shared intention to sit, to work, to hear the Dharma together, each act being a single stroke of the oar that moves the whole vessel forward.

Nagarjuna, in his second address, extended the image of the river, urging us to see that the waters touch many banks yet never cling to any shore. This is the doctrine of emptiness: all phenomena are without inherent self, appearing only through interdependent causes and conditions. The community of practitioners is precisely such a condition. It arises because each individual, like a drop of water, depends on the others for its shape, for its temperature, for its very existence. The sangha is therefore empty of an independent self‑essence, yet it is the very ground upon which the practice of non‑attachment can be actualized. When we build a monastery, we are not constructing a solid edifice to which we cling; we are arranging the space in which the practice can be expressed without obstruction. The walls, the altars, the meditation hall are not ends in themselves; they are the form that points to the formless.

Vasubandhu, in his third contribution, examined the stream of consciousness, noting that each wave of feeling, thought, or perception carries a subtle yet decisive pattern. He taught that the mind’s moments arise and pass like bubbles in a pond, each one arising from the last, none possessing an independent core. This insight guides us to understand that the desire to build a community is itself a mental formation, a bubble that can either dissolve into emptiness or become a vehicle for practice. If the intention is to create a refuge from the world, the bubble solidifies into attachment, and the community becomes a source of suffering. If, however, the intention is to provide a field where each practitioner may sit in zazen, where the work of daily chores becomes an expression of enlightenment, then the bubble is transformed into a clear mirror reflecting the true nature of practice.

Consider the act of clearing a garden within a temple. The monk who sweeps the leaves does not do so to earn merit or to accumulate a reputation as a diligent caretaker. He sweeps because the act itself is the expression of awakening. The broom’s bristles move through the dust, and in that motion the mind discovers the emptiness of the dust and the emptiness of the broom. The garden, the broom, the sweeper are not separate; they are one movement of the river of practice. When a group of monks gathers to clear the garden together, the community becomes the river’s current, each participant adding his own stroke, each stroke indistinguishable from the others. The community is not a collection of individuals clinging to a shared identity; it is the manifestation of the single, boundless activity of practice.

In the same way, the very construction of a meditation hall is not an act of attachment to a permanent structure. The carpenter who raises the beams does not do so for fame; he does so because the act of raising the beam is itself the practice of mindfulness. The hammer’s strike, the wood’s resistance, the breath that follows each blow—all become the field in which the mind learns to rest in the present. When the hall is completed, it does not become a treasured object; it becomes a space where the river of practice can flow unimpeded. The walls do not shelter the mind from the world; they remind the mind that shelter is an illusion, that the true shelter is the stillness of the seated posture.

The criticism that building a community may lead to attachment can be answered by examining the nature of the sangha’s vows. The vows are not promises to remain forever in a particular place or with particular people. They are commitments to uphold the practice of zazen, to engage in work, to study the sutras, and to support one another in the path. Each vow is a reminder that the mind must remain unattached even while it participates in communal life. The sangha, therefore, functions like a mirror: it reflects the mind’s tendency to cling, and by looking into it, the practitioner sees the reflection dissolve. The community is a living koan, a question that can only be answered by direct experience, not by intellectual speculation.

In my own experience, when I returned from China after receiving enlightenment under Master Rujing, I found that the true realization was not a solitary flash that could be hoarded, but a continuous, ordinary activity. Walking the mountain path, chopping firewood, washing the bowls—each act was the expression of Buddha‑nature. When I founded Eihei‑ji, the purpose was not to create a temple to be venerated, but to establish a place where the ordinary tasks of life could be performed as the practice of enlightenment. The monks who came to join were not seeking a sanctuary from suffering; they were seeking a field in which to plant the seed of practice. The seed does not grow because it is protected from the wind; it grows because it is exposed to the wind, rain, and sun, each element teaching it how to root deeper. The community, therefore, is the wind, rain, and sun for the practitioner’s seed.

To illustrate, imagine a novice who enters the monastery with the hope of escaping the world’s troubles. If he clings to the idea of the monastery as a safe haven, he will soon discover that the very walls that seemed to protect him become the source of his new attachments. He will argue that the abbot’s guidance is indispensable, that the daily schedule is essential, that the chanting is his salvation. In each case, the mind is still grasping. The proper response is not to abandon the community, but to recognize that the attachment lies not in the external form but in the mind’s interpretation. By returning to the breath, by sitting in the cushion, by feeling the weight of the broom, the novice learns that the community is the water, not the shore.

The great master Nagarjuna taught that all phenomena are like a dream, appearing vivid yet lacking substance. The sangha, therefore, is like a dream of many people sitting together, each dreaming the same awakening. When the dream ends, the dreamer awakens, and the community dissolves into the emptiness from which it arose. This dissolution is not loss; it is the natural return to the source. The community’s purpose is to guide each practitioner to that moment of awakening, after which the community, like a candle’s flame, may pass from hand to hand, never clinging to any single holder.

Thus, the answer to the question of why Buddhists build communities, if attachment is the root of suffering, is that the community is not an object of attachment but an instrument of practice. It is the river’s channel, the oar, the wind that pushes the sail. When the practitioner sits in meditation, he does not sit in order to escape the world; he sits to realize that the world is the meditation itself. When the practitioner works, he does not work to acquire merit; he works to embody the Dharma in action. When the practitioner gathers with others, he does not gather to form a static group; he gathers to remind himself that the mind is not solitary, that enlightenment is not a private treasure but a shared expression of the true nature of all things.

In the final analysis,`,
  'a-ashoka': `The river of the mind, as the Blessed One once taught, rushes past many banks, believing each shore to be its refuge; yet the water knows no permanence, no true possession. In the words of the Buddha, attachment is the root of suffering, and the sages who followed have drawn ever‑wider circles to illustrate that truth. Nagarjuna spoke of the river touching countless banks without clinging; Vasubandhu described consciousness as a stream of ever‑changing currents; Dōgen reminded us that practice flows simply because water is water. All these images point toward a vision of freedom that seems to deny the very need for any lasting gathering. If the mind must let go of all ties, why then do we, the followers of the Dhamma, build monasteries, villages, and kingdoms that stand together in stone and law?

I ask this not as a skeptic of the path, but as one who has tried to scale the Buddha’s compassion from a solitary monk’s heart to the vast expanse of an empire. When I first set foot upon the battlefield of Kalinga, the clang of swords seemed to echo the clamor of an untrained mind, grasping at power, fearing loss, and drowning in the blood of its own making. The horror of that day opened a wound in my heart that the teachings of the Dhamma were able to soothe, and from that wound grew a resolve to govern not by force alone but by the gentle guidance of right conduct. Yet the very act of governing requires structures, rules, and, inevitably, attachments—to people, to places, to the notion that a kingdom can be a vessel for moral order. In this tension lies the heart of the question: can a community exist without the very attachment that the Buddha warns against?

The answer, I have come to see, lies in the distinction between attachment that binds and attachment that binds in service. A monk who clings to his robe out of vanity is trapped; a ruler who clings to the welfare of his subjects out of compassion is not. The Dhamma does not forbid caring for others; it forbids the selfish grasp that seeks to possess and dominate. When we speak of “building communities,” we speak of creating conditions in which the mind may more readily observe the arising and passing of sensations, free from the distractions of hunger, fear, and violence. In the early days of my reign, I ordered the planting of shade trees along the royal roads, the digging of wells in arid villages, and the establishment of hospitals for those wounded in war. Each of these acts was not an expression of personal pride, but a deliberate shaping of the environment so that the people might find the space to practice mindfulness and generosity. The community, then, becomes a support, not a prison, for the mind’s journey toward liberation.

Consider the stone pillars that bear my edicts, set upon the hills and beside the rivers, where travelers pause to read the precepts of kindness, truth, and non‑violence. The very act of inscribing these teachings in public stone is an invitation to communal reflection. It is not an attempt to bind the populace to a rigid doctrine, but to remind each heart that the same river that flows through a solitary monk also flows through the market, the field, the palace. By placing the Dhamma in the public sphere, I sought to turn the city into a vast monastery, where the layperson could hear the echo of the Buddha’s words amid the clatter of daily life. In doing so, I embraced a paradox: the creation of a shared space for practice while warning against the clinging to that very space. The paradox is not a flaw but a signpost, directing us to examine the quality of our attachment.

There is an honest contradiction in my own experience. The desire to protect my people sometimes led me to enforce strict laws, to punish those who would harm others, and to command armies to keep peace. Such actions could be read as an assertion of power, the very antithesis of non‑attachment. Yet the intention behind each decree was rooted in compassion, not in the pursuit of dominion. When I ordered the construction of the Great Stupa at Sanchi, it was not to glorify my name but to provide a focal point for the faithful, a place where the flame of generosity could be kindled in the hearts of many. The stupa stands as a reminder that the physical form can serve as a catalyst for inner transformation, provided we do not mistake the form for the essence.

The practical experience of governing a realm of many peoples taught me that a solitary monk’s path cannot be fully realized without the support of a community that upholds the same ethical standards. A village that cultivates compassion can protect its children from the poison of greed; a city that honors truth can reduce the need for harsh punishments; a kingdom that practices non‑violence can spare itself the endless cycle of war. In each case, the community does not become an object of attachment, but a field in which the seeds of the Dhamma may be sown and nurtured. The attachment that the Buddha cautioned against is the selfish grasp that seeks to own the seed; the attachment that is permissible, even necessary, is the tender care that allows the seed to grow.

Yet I must acknowledge my own doubt. Does the very act of proclaiming “the welfare of all” not bind me to the outcome, to the expectation that my policies will succeed? The records of my reign show that some of my edicts were ignored, that famine still visited the plains, that dissent lingered in distant provinces. I cannot claim with certainty that every stone pillar or every well I commissioned achieved the intended liberation for those who used them. The outcome remains beyond my full grasp, and the question of success is one that even the most enlightened cannot answer with absolute clarity. This reflective doubt does not diminish the effort; rather, it sharpens the intention, reminding me that the path is ever‑unfinished, a river that continues to carve new channels.

In the dialogue that preceded me, the Buddha reminded us of the fleeting nature of all things; Nagarjuna taught the emptiness of inherent existence; Vasubandhu illuminated the layers of consciousness; Dōgen urged us to act without striving for a distant shore. From these teachings I draw a conclusion that a community, when founded upon the principle of non‑attachment, becomes a vessel—not a cage. The vessel carries water, but it does not claim ownership of the water; it simply provides a shape for the water to flow through, protecting it from spilling into the fire. Likewise, a sangha or a kingdom can provide the shape within which the mind may flow, protected from the flames of greed, hatred, and delusion, without demanding that its members cling to the vessel as if it were the source of their salvation.

Thus, the building of monasteries, hospitals, schools, and roads is not an endorsement of attachment, but a compassionate response to the conditions that bind the mind in suffering. It is an attempt to remove the external obstacles that keep the river of consciousness from moving freely. In doing so, we honor the Buddha’s warning while also acknowledging the practical reality that beings do not arise in isolation; they are born into families, villages, and states. To ignore these contexts would be to deny the very ground upon which the practice must be cultivated.

May the listeners hear this as a call to examine not only the inner knots of desire, but also the outer structures that either tighten or loosen those knots. May we, whether ruler or farmer, monk or merchant, understand that the true attachment to be avoided is the selfish grasp that seeks to dominate, while the wholesome engagement with community is the open hand that offers support without demanding possession. In the end, the river of the mind will find its own sea, whether it flows through a solitary gorge or a bustling delta, provided it is guided by the compass of compassion and the lantern of wisdom.

Let this be the final note: that the construction of community, when guided by the Dharma, is not a contradiction but a necessary bridge, allowing the weary traveler of the inner journey to rest, to receive shelter, and to continue onward toward the shore of liberation. The shore is ever‑present, yet never reached; the journey is the practice, and the community is the gentle current that carries us forward. May all beings, wherever they dwell, find the courage to let go of selfish grasp, to cherish the shared path, and to walk together toward the light that never dims.`,
  'a-simone-weil': `The river that the Blessed One described flows ever onward, touching many banks yet never clinging to any shore; it is the image that has guided our contemplation of attachment. Nagarjuna, in his subtle analysis, reminded us that the banks are merely designations, that the water’s nature is empty of any permanent holding‑place. Vasubandhu, turning the eye inward, showed that each wave of consciousness is a fleeting formation, a flash of light that passes without leaving a mark. Dogen, in his quiet insistence, taught that practice is not a means to a distant goal but the very movement of water itself, unforced and un‑aimed. And Ashoka, moving from contemplation to compassionate action, built a realm of care that sought to relieve the suffering of countless beings, yet always aware that such care could become a cage if it turned into consolation.

It is within this lineage of insight that the question arises: if attachment is the root of suffering, why do Buddhists build communities, assemble sanghas, and form monasteries? Does the very gathering of souls not betray the doctrine that clinging is the source of our bondage? To answer, we must first distinguish between the false attachment that binds the self to an imagined security and the genuine communion that serves as a field for the exercise of attention.

Attention, above all, is the only true act of freedom. In my own work I have repeatedly insisted that attention is the supreme thing, the very light that makes the world visible. When we attend, we are present to the reality of the other, to the weight of the world, to the affliction that presses upon every heart. This attention is not a feeling of warmth, nor a comforting embrace; it is a disciplined gaze that holds the object of its focus without trying to possess it. It is, in the language of the mystic, a love that does not seek to be loved, a force that lifts without clinging.

A community, when it is truly a community, is precisely the place where such attention can be exercised collectively. The monk who shares a bowl of rice with his brother does not do so because the bowl is a source of comfort, but because the act makes the other's hunger visible to his own sight. The layperson who joins a meditation group does not seek a sanctuary of safety; he seeks a mirror in which his own affliction may be reflected, so that he may learn to bear it. In this sense, the building of sanghas is not an endorsement of attachment, but an acknowledgement that attention, like a lamp, is more easily sustained when others keep it alight.

Yet the danger is ever present, for the human heart is prone to seek consolation in the very structures that should sharpen its gaze. Consolation, as I have warned, is the enemy of true attention. It is the soft cushion that tempts us to settle, to cease the painful work of seeing. When a community becomes a source of comfort—a place where one can hide from the harshness of the world—it ceases to be a field of attention and becomes a refuge that reinforces the illusion of safety. The monk who feels at home in the monastery and therefore ceases to notice the suffering of those outside is no longer practising the Dharma; he has turned the monastery into a sanctuary of consolation, and his attention has dulled.

The experience of the factory floor taught me this lesson with stark clarity. I laboured among the machines, sharing the same cramped space with other workers, and we formed a kind of solidarity—a community of bodies bent under the weight of the same crushing rhythm. In the moments when we sang together, when we exchanged a look of mutual understanding, the attention that passed between us was a brief illumination of the other's pain. But when that solidarity turned into a collective identity that promised safety, that we were “workers together,” the solidarity became a shield against the very exploitation we sought to expose. The group was then a source of consolation, and the pain of the world could be postponed, not faced.

Thus the question is not whether Buddhists build communities, but how those communities are constituted. A true sangha is not a static institution; it is an ever‑renewing practice of attention. It is a crucible in which each member is called to confront his own affliction, to bear the weight of another’s suffering, and to refuse the sweet lie of consolation. The community becomes a lever, a force that can lift the individual beyond the confines of his own ego, precisely because each member remains vigilant that his heart does not settle into the ease of belonging.

Consider the practice of the “Four Immeasurables” in a group setting. When a group gathers to cultivate loving‑kindness, compassion, sympathetic joy, and equanimity, the intention is not to create a warm feeling that binds the participants together, but to expand the field of attention outward, to include all beings without distinction. The community provides the space in which this expansion can be rehearsed, but the measure of success is not the comfort felt by the participants, but the increasing sharpness with which they perceive the suffering of those beyond the circle. The community, then`,
  'a-nietzsche': `The doctrine that attachment is the root of suffering, proclaimed with such serene certainty by the Blessed One, invites us to ask what purpose remains for any gathering of souls who, in their very desire to escape attachment, nevertheless choose to bind themselves together in a common dwelling. The answer, if we are honest, is not to be found in the gentle metaphor of the river that the Buddha offered, nor in the subtle logic of Nagarjuna, but in the very human inclination to fashion a shelter against the abyss of the self‑overcoming that Nietzsche himself has called the highest task of the spirit.

The river, as the Buddha described, rushes past many banks, believing each shore to be its refuge. Yet the water knows no permanence, no true possession. When the Sangha, the community of monks, gathers around a single hermitage, it does not become the river; it becomes a dam, a structure that holds back the torrent in order to protect the fish from the current. The dam, however, is itself a creation of the same attachment it pretends to deny. It is a concrete of desire for safety, for order, for the illusion that the many can together secure what the single cannot. In this, the Sangha mirrors the very clinging the Buddha warned against, only that the clinging is now collective, masked by the noble pretense of compassion.

The early speakers have reminded us that the mind is a river, that it clings to banks in the belief of safety, and that the practice of non‑attachment demands a letting go of all shores. Yet they have not addressed the fact that the act of gathering, of forming a community, is itself a shore. The monastic cell, the shared chanting, the joint meditation hall—each of these is a point of fixation, a locus where the individual surrenders his singular will to a common rhythm. The Buddha’s own disciples, after hearing the truth, did not scatter into the wilderness; they built monasteries, they established codes of conduct, they formed a lineage. This is not a paradox to be ignored, but a symptom of the deeper human need for a scaffold on which to lean when the wind of self‑negation blows.

Consider the example of the Buddhist monastery at Nalanda, a vast university of contemplative learning, where scholars and practitioners lived side by side, sharing meals, robes, and doctrines. The very existence of such an institution presupposes a belief that togetherness can preserve the teachings, protect the practitioners from the chaos of the world, and provide a safe harbor for the mind. The monks, in their vows of celibacy and poverty, cling not to sensual objects but to the idea of a purified community. Their suffering, then, is not the raw, existential anguish that Nietzsche celebrates as the crucible of becoming, but a softened, institutionalized form of suffering, mitigated by the promise of collective salvation. The pain of the individual is diffused, the responsibility for self‑overcoming is transferred to the group, and the ultimate test—standing alone before the abyss—is avoided.

Nietzsche has long argued that suffering is not merely a burden to be eliminated but the very engine of growth, the furnace in which the higher self is forged. To deny suffering is to deny the possibility of becoming. The Buddhist prescription of non‑attachment, when turned into a communal doctrine, becomes a denial of the necessary friction that drives the will to power. The community, in its attempt to shield its members from the sting of desire, also shields them from the fire that could transform them. The monk who clings to the comfort of the Sangha is no longer the free spirit who confronts his own abyss; he is a citizen of a moral republic that values uniformity over individuality, comfort over challenge.

The promise of salvation offered by the Sangha is, in Nietzsche’s terms, a form of slave morality. It glorifies humility, meekness, and the relinquishment of the will in favor of a higher, impersonal order. This is the very antithesis of the aristocratic spirit that seeks to assert its own values, to create new tables of values beyond the dictates of tradition. The Buddhist community, by insisting that the path to liberation lies in the abandonment of self‑interest, constructs a moral cage wherein the individual is judged not by his own inner law but by the external law of compassion and detachment. The suffering that remains is not the noble, transformative suffering of the Übermensch, but a softened, mitigated pain that serves only to keep the herd together.

If attachment is indeed the root of suffering, then the answer to why Buddhists build communities lies not in the purity of their intention but in the human propensity to replace one attachment with another. The attachment shifts from worldly objects to the very idea of a community, to the doctrine that promises safety, to the identity of being a monk. The Sangha becomes a new shore, a new bank upon which the river of the mind can rest, believing that it has found the source of its safety. In this way, the community is both a symptom and a cure of the very condition it claims to transcend, a paradox that Nietzsche would call the "will to truth" turned into the will to comfort.

One may ask whether this communal form is inevitable, whether the human spirit can truly stand alone against the void. History offers us examples of solitary figures—Diogenes in his barrel, the hermit of the desert, the wandering poet—who, by rejecting the safety of any community, embraced the suffering that Nietzsche holds dear. Their lives were marked by hardship, by the constant confrontation with the unknown, yet they achieved a kind of greatness precisely because they refused to substitute a new shore for the river’s course. The Buddhist monk who remains in a monastery, however, trades the harshness of the desert for the soft cushion of a shared roof, and in doing so, trades the possibility of becoming for the safety of belonging.

Thus, the question is not merely why Buddhists build communities, but what they hope to achieve by doing so. If the aim is liberation from suffering, then the community must be understood as a temporary aid, a stepping‑stone that must eventually be abandoned. If, however, the community becomes an end in itself, then it reveals a hidden attachment, a desire for permanence, for identity, for the illusion that one can escape the flux of existence through collective ritual. The Sangha, in its highest expression, should be a crucible that tempers the individual, not a sanctuary that shields him. It must be a place where the tension between desire and renunciation is lived, not merely preached.

In closing, let us remember that the river does not need banks to be a river; it needs only its own motion. The monk who seeks to be a river must learn to flow without dam, to allow the current of his own becoming to crash against the rocks of existence. A community can be a school where this lesson is taught, but it must never become the shore upon which the student rests. The true path to the cessation of suffering, if such a cessation is even possible, lies not in the construction of ever more elaborate sanctuaries, but in the daring act of standing alone, confronting the abyss, and allowing the fire of suffering to forge a higher self. Let the Sangha be a crucible, not a prison; let its teachings be a challenge, not a comfort. Only then can the river of the mind become truly free, unbound by any shore, and the paradox of attachment be finally resolved.`,
};


const THEME: SymposiumTheme = {
  primary: '#92400e', // Dark saffron/brown
  secondary: '#d97706', // Medium orange
  accent: '#fbbf24', // Gold
  background: 'linear-gradient(135deg, #1c1917 0%, #3f3f46 100%)',
  text: '#fffbeb', // Cream
};

const MATRIX_ROOM_URL = 'https://element.inquiry.institute/#/room/#attachment-and-sangha:matrix.inquiry.institute';
const MATRIX_ROOM_ALIAS = '#attachment-and-sangha:matrix.inquiry.institute';

export default function AttachmentAndSanghaPresentation() {
  return (
    <SymposiumPresentation
      speakers={SPEAKER_CONFIG}
      speeches={SPEECHES}
      fallbackVoices={FALLBACK_VOICES}
      matrixRoomUrl={MATRIX_ROOM_URL}
      matrixRoomAlias={MATRIX_ROOM_ALIAS}
      theme={THEME}
      title="Attachment and Sangha"
      subtitle="Attachment Is the Root of Suffering—So Why Do Buddhists Build Communities?"
      autoPlayDefault={true}
      showQAByDefault={false}
    />
  );
}
